<script type="text/javascript" src="${ctx }/js/bootstrap-fileupload.min.js"></script>
<script type="text/javascript" src="${ctx }/js/bootstrap-timepicker.min.js"></script>
<script type="text/javascript" src="${ctx }/js/jquery.uniform.min.js"></script>
<script type="text/javascript" src="${ctx }/js/jquery.validate.min.js"></script>
<script type="text/javascript" src="${ctx }/js/jquery.tagsinput.min.js"></script>
<script type="text/javascript" src="${ctx }/js/jquery.autogrow-textarea.js"></script>
<script type="text/javascript" src="${ctx }/js/charCount.js"></script>
<script type="text/javascript" src="${ctx }/js/colorpicker.js"></script>
<script type="text/javascript" src="${ctx }/js/ui.spinner.min.js"></script>
<script type="text/javascript" src="${ctx }/js/chosen.jquery.min.js"></script>
<script type="text/javascript" src="${ctx }/js/forms.js"></script>